### ISSUE TITLE
Uber Zap import is incorrect in multiple places

### ISSUE THREAD

**Issue by mttdbrd** [IBM-Cloud/go-etcd-rules#38]
`src/github.com/IBM-Bluemix/go-etcd-rules/rules/crawler.go:9:2: code in directory /home/someuser/workspace/gocode/src/github.com/uber-go/zap expects import "go.uber.org/zap"`

Once the imports are fixed, we see the following issue:

`src/github.com/IBM-Bluemix/go-etcd-rules/rules/crawler.go:162: cannot use logger (type *zap.Logger) as type zap.Logger in argument to ec.baseCrawler.kp.processKey
src/github.com/IBM-Bluemix/go-etcd-rules/rules/crawler.go:220: cannot use logger (type *zap.Logger) as type zap.Logger in argument to v3ec.baseCrawler.kp.processKey
src/github.com/IBM-Bluemix/go-etcd-rules/rules/engine.go:308: cannot use logger (type *zap.Logger) as type zap.Logger in argument to newCrawler
src/github.com/IBM-Bluemix/go-etcd-rules/rules/engine.go:321: cannot use logger (type *zap.Logger) as type zap.Logger in argument to newWatcher
src/github.com/IBM-Bluemix/go-etcd-rules/rules/engine.go:348: cannot use logger (type *zap.Logger) as type zap.Logger in argument to newV3Watcher
src/github.com/IBM-Bluemix/go-etcd-rules/rules/int_crawler.go:157: cannot use logger (type *zap.Logger) as type zap.Logger in argument to ic.kp.processKey
src/github.com/IBM-Bluemix/go-etcd-rules/rules/worker.go:140: cannot use task.Logger.With(zap.String("worker", w.baseWorker.workerID)) (type *zap.Logger) as type zap.Logger in assignment
src/github.com/IBM-Bluemix/go-etcd-rules/rules/worker.go:151: cannot use task.Logger.With(zap.String("worker", w.baseWorker.workerID)) (type *zap.Logger) as type zap.Logger in assignment`

**Comment by mttdbrd** [comment]
The pull request from @mirskifa fixes this issue.

**Comment by HellenWang** [comment]
I faced the same issue, could anyone fix this issue?

**Comment by ericmillin** [comment]
Please. This is causing lots of problems.

**Comment by jswarren4** [comment]
It was using the beta version of zap which could be used by pinning the github version.  In any case, this has been resolved by https://github.com/IBM-Cloud/go-etcd-rules/pull/75
