### ISSUE TITLE
Add stacktrace to panic recover

### ISSUE THREAD

**Issue by cocoztho000** [IBM-Cloud/go-etcd-rules#73]
It was hard to debug a panic in the logs coming from this line: https://github.com/IBM-Cloud/go-etcd-rules/blob/master/rules/worker.go#L159 since there is no stack trace in the error.  

The recover in the link above was capturing a panic from my service but i couldn't tell since it looked like it was coming from the crawler.

**Comment by kramvan1** [comment]
outdated
