### ISSUE TITLE
switch to go.etcd.io/etcd

### ISSUE THREAD

**Issue by chriskirkland** [IBM-Cloud/go-etcd-rules#84]
etcd was recently [migrated](https://github.com/etcd-io/etcd/pull/10044) from github.com/cores to github.com/core-io (go.etcd.io vanity prefix).  They have yet to cut a release with those changed import paths.  We should switch to go.etcd.io/etcd as the import path once they do and are stable.

**Comment by philips** [comment]
releases have been cut with this new import path.

**Comment by kramvan1** [comment]
done 3.4.x client
